def userId = "bala"

echo  "$userId"

def fruit_fans = '[ "$userId","bob","zoe"]'

def choices = []
if  (fruit_fans.contains("$userId")) {
    choices = ["Apple","Banana","Cherry"]
} else {
    choices = ["Amaranth","Beet","Cabbage"]
}


properties([
    parameters([
        [
            $class: 'ChoiceParameter',
            choiceType: 'PT_MULTI_SELECT',
            description: 'Active Choices Reactive parameter',
            filterLength: 1,
            filterable: false,
            name: 'food',
            referencedParameters: 'role',
            script: [
                $class: 'GroovyScript',
                fallbackScript: [
                    classpath: [],
                    sandbox: false,
                    script: 'return ["error"]'
                ],
                script: [classpath: [],
                    sandbox: false,
                    script: 'return $choices'
                ]
            ]

        ]
    ])
])

node {
    stage("Show Selection"){
        echo "$userId selected $food" 
    }
}
